import React from 'react';
import { notFound } from 'next/navigation';
import Link from 'next/link';
import { CheckCircle2, FileText, HelpCircle, ArrowRight } from 'lucide-react';
import ContactForm from '@/components/ContactForm';
import type { Metadata } from 'next';

// Product configurations
const PRODUCT_DATA: Record<string, {
  name: string;
  heroDesc: string;
  rates: string;
  amount: string;
  tenure: string;
  benefits: string[];
  eligibility: string[];
  documents: { salaried: string[]; selfEmployed?: string[] };
  processSteps: string[];
  faqs: { q: string; a: string }[];
}> = {
  'personal-loan': {
    name: 'Personal Loan',
    heroDesc: 'Compare and secure instant, collateral-free personal credit up to ₹40 Lakhs from India\'s top banking partners with direct consulting support.',
    rates: '10.49% - 21.00% p.a.',
    amount: 'Up to ₹40 Lakhs',
    tenure: '1 to 7 Years',
    benefits: [
      'Collateral-free unsecured credit line.',
      'Flexible tenure options ranging from 12 to 84 months.',
      'Disbursement directly into primary salary account in 24-48 hours.',
      'Option to foreclose or prepay with low charges.',
    ],
    eligibility: [
      'Minimum net monthly salary: ₹15,000 onwards.',
      'Age limit: 21 Years to 60 Years.',
      'Credit Score: 700 or above preferred.',
      'Employment status: Salaried at a registered Private, MNC, or Govt entity with 1+ year vintage.',
    ],
    documents: {
      salaried: [
        'Aadhaar Card and PAN Card.',
        'Address Proof (Rent agreement / Utility bill / Voter ID).',
        'Last 3 Months Salary Slips.',
        'Last 6 Months Bank Statement (showing salary credits).',
        'Form 16 or ITR details (last 2 years).',
      ]
    },
    processSteps: [
      'Submit your parameters via our online consultation form.',
      'Our credit engine maps your details against eligible bank parameters.',
      'Assigned executive verifies your KYC and collects bank statement PDFs.',
      'Direct underwriting team reviews the file and issues disbursement.',
    ],
    faqs: [
      { q: 'What is the processing fee for a Personal Loan?', a: 'Processing fees range from 1% to 3.5% of the loan amount, deducted by the lender during disbursement.' },
      { q: 'Can I foreclose my Personal Loan early?', a: 'Yes. Most partner banks allow foreclosure after paying 6 to 12 EMIs, subject to foreclosure charges of 2% to 5%.' }
    ]
  },
  'business-loan': {
    name: 'Business Loan',
    heroDesc: 'Acquire collateral-free business expansion capital up to ₹75 Lakhs. Streamlined submissions, GST integration, and fast-track processing.',
    rates: '13.99% - 24.00% p.a.',
    amount: 'Up to ₹75 Lakhs',
    tenure: '1 to 5 Years',
    benefits: [
      'Zero physical collateral or asset security required.',
      'GST & ITR based credit evaluation pathways.',
      'Flexible capital usage: Inventory procurement, expansion, or salary clearance.',
      'High approval rates for MSMEs with clean cash flow profiles.',
    ],
    eligibility: [
      'Eligibility: Based on Business Turnover.',
      'Business Vintage: Continuous operations of 2+ years.',
      'Promoters credit score: 720 or above.',
      'GST returns: Regular GSTR-3B filings for the last 12 months.',
    ],
    documents: {
      salaried: [
        'PAN Card of promoters and the business entity.',
        'GST Registration Certificate & 12 Months GSTR-3B filings.',
        'Last 12 Months Business Bank Statements.',
        'ITR and Balance Sheet / Profit & Loss Statement (last 2 financial years).',
        'Office address ownership proof or lease contract.',
      ]
    },
    processSteps: [
      'Enter business turnover, GST registration status, and income.',
      'Consultant reviews banking parameters and checks eligibility.',
      'Upload audited financial Statements and 1-year GST records.',
      'Sanction letter is generated by partner bank in 3-5 working days.',
    ],
    faqs: [
      { q: 'Is collateral mandatory for a Business Loan?', a: 'No, we specialize in facilitating collateral-free unsecured business loans based on GST turnovers and bank cash flows.' },
      { q: 'Can proprietary firms apply for business credit?', a: 'Yes, proprietorships, partnerships, and Private Limited companies are all eligible to apply.' }
    ]
  },
  'home-loan': {
    name: 'Home Loan',
    heroDesc: 'Step into your dream home with interest rates starting from 8.40%. Flexible tenures up to 30 years, low processing fees, and co-applicant benefits.',
    rates: '8.40% - 11.50% p.a.',
    amount: 'Up to 90% of Property Value',
    tenure: '5 to 30 Years',
    benefits: [
      'Lowest interest rates compared to other retail credit products.',
      'Long tenure limits (up to 30 years) to keep EMIs affordable.',
      'Balance transfer options to switch from high-interest lenders.',
      'Substantial tax deductions under Section 24 and Section 80C.',
    ],
    eligibility: [
      'Age limit: 21 Years to 65 Years at loan maturity.',
      'Income: Net monthly income of ₹15,000 onwards (Salaried) or ITR of ₹4 Lakhs (Self Employed).',
      'Credit Score: 750 or above guarantees the cheapest interest rate slabs.',
      'Property: Clear legal titles and approved builders preferred.',
    ],
    documents: {
      salaried: [
        'Aadhaar and PAN Card.',
        'Last 3 Months Salary Slips (Salaried) or 2 Years ITR (Self Employed).',
        'Last 6 Months Bank Statement.',
        'Property documents: Draft sale agreement, approved builder layout plans, chain documents.',
      ]
    },
    processSteps: [
      'Select property details, income metrics, and tenure.',
      'We check rates across 25+ lenders and builder approval status.',
      'KYC, income papers, and legal property copies are collected.',
      'Bank legal/technical team inspects property and issues disbursement.',
    ],
    faqs: [
      { q: 'Are there foreclosure charges on Home Loans?', a: 'Per RBI guidelines, floating interest rate home loans have zero foreclosure or prepayment penalties.' },
      { q: 'Can I add a co-applicant to increase my loan limit?', a: 'Yes, adding working family members as co-applicants combines incomes and boosts eligibility.' }
    ]
  },
  'loan-against-property': {
    name: 'Loan Against Property',
    heroDesc: 'Unlock high-value liquidity by leveraging the market value of your residential, commercial, or industrial property at lower interest rates.',
    rates: '9.00% - 13.00% p.a.',
    amount: 'Up to ₹15 Crores',
    tenure: '5 to 20 Years',
    benefits: [
      'Much cheaper interest rates compared to personal or business loans.',
      'Unlocks massive funds (up to 70% of property market value).',
      'Repay comfortably with tenures up to 20 years.',
      'Applicable on both residential houses and commercial shops.',
    ],
    eligibility: [
      'Age: 21 Years to 65 Years.',
      'Income: Steady salary or business profits matching proposed EMI obligations.',
      'Credit Score: 700 or above.',
      'Property: Must have clear legal titles, occupied or rented, and structurally sound.',
    ],
    documents: {
      salaried: [
        'Aadhaar and PAN Card.',
        'Income proof (3 salary slips or 2 years business financials).',
        'Original property title deeds, parent deeds, approved maps.',
        'Last 6 months bank statement showing regular transactions.',
      ]
    },
    processSteps: [
      'Submit property type (Commercial/Residential) and estimated market value.',
      'Advisory team matches property parameters with banking policies.',
      'Assigned executive collects technical plans and property deeds.',
      'Direct valuation by bank surveyors, followed by loan disbursal.',
    ],
    faqs: [
      { q: 'Can I keep a rented commercial property as collateral?', a: 'Yes, rented commercial shops, offices, and warehouses with lease rent discounting are eligible.' },
      { q: 'What is the LTV ratio for LAP?', a: 'LTV ranges from 50% to 70% of the verified market value of the property, depending on the bank.' }
    ]
  },
  'credit-card': {
    name: 'Credit Cards',
    heroDesc: 'Maximize cashbacks, flight miles, and dining rewards. Compare premium credit cards across major bank partners and apply online.',
    rates: 'Interest-free up to 50 days',
    amount: 'Custom Limits based on profile',
    tenure: 'N/A',
    benefits: [
      'Earn reward points, air miles, or direct cashbacks on transactions.',
      'Airport lounge access, dining discounts, and golf games privileges.',
      'Establish and build credit history for future high-value loans.',
      'EMI conversion options on major retail or online purchases.',
    ],
    eligibility: [
      'Age limit: 18 Years to 60 Years.',
      'Income: Net monthly income of ₹20,000 (Salaried) or ITR of ₹3 Lakhs.',
      'Minimum Credit Score Required: 700+ CIBIL Score.',
      'Existing card holder: Card-to-card application available if current card limit > ₹50,000.',
    ],
    documents: {
      salaried: [
        'Aadhaar and PAN Card.',
        'Latest Salary Slip / Form 16 / ITR copy.',
        'Latest Credit Card Statement (if applying under Card-to-Card protocol).',
      ]
    },
    processSteps: [
      'Select reward preference (Cashback, Travel, Shopping, Lounge).',
      'System filters matching credit cards across premium partner banks.',
      'Fill required KYC and submit digital verification links.',
      'Physical card is shipped to residence in 3-5 business days.',
    ],
    faqs: [
      { q: 'Is there an annual fee on credit cards?', a: 'Some cards are Lifetime Free (LTF), while others charge an annual fee that is waived off upon crossing yearly spend limits.' },
      { q: 'How does card-to-card application work?', a: 'If you have an active card from another bank, you can apply using its statement. No additional salary proofs are required.' }
    ]
  },
  'project-loan': {
    name: 'Project Loan',
    heroDesc: 'Secure customized funding for large-scale infrastructure, real estate, manufacturing, or commercial projects. Map your requirements with direct underwriting paths.',
    rates: '9.50% - 15.00% p.a.',
    amount: 'Up to ₹100 Crores',
    tenure: '3 to 15 Years',
    benefits: [
      'Structured credit limits mapped to construction or setup stages.',
      'Flexible moratorium/grace periods during project execution.',
      'Competitive interest rates and customized repayment tenures.',
      'Direct facilitation link with top corporate bank underwriters.',
    ],
    eligibility: [
      'Eligibility: Based on Documents & Project Profile.',
      'Promoters business vintage: 3+ years in a related industry.',
      'Project feasibility reports (TEV study / business plan) ready.',
      'Clear land titles or lease contracts for project execution.',
    ],
    documents: {
      salaried: [
        'PAN Card of the corporate entity and promoters.',
        'TEV Report, project business plan, and financial projections.',
        'Audited financials, tax records, and balance sheets (last 3 financial years).',
        'Land purchase deed / lease agreement / construction contracts.',
      ]
    },
    processSteps: [
      'Submit project concept note and estimated capital required.',
      'Advisory team audits TEV reports and checks matching lender limits.',
      'Assigned expert represents the project file directly to bank boards.',
      'Due diligence review, project sanction, and milestone-wise disbursement.',
    ],
    faqs: [
      { q: 'What is a TEV study?', a: 'TEV stands for Techno-Economic Viability study. Lenders require this report to evaluate the technical feasibility and economic profitability of the project.' },
      { q: 'Can we get a moratorium period for repayments?', a: 'Yes. Project loans typically include a principal moratorium period (grace period) during construction or setup stages.' }
    ]
  },
  'top-up-loan': {
    name: 'Top-up Loan',
    heroDesc: 'Get additional, low-cost liquidity over your existing home or property loan. Quick approval, minimal documentation, and attractive retail rates.',
    rates: '8.65% - 12.00% p.a.',
    amount: 'Up to ₹1 Crore',
    tenure: 'Up to 20 Years',
    benefits: [
      'Interest rates significantly lower than personal or business loans.',
      'Minimal documentation required as primary home/property loan details already exist.',
      'Flexible usage: Home renovation, business cash flow, or education expenses.',
      'Tax benefits if utilized for home construction or renovation.',
    ],
    eligibility: [
      'Must have an active primary Home Loan or Loan Against Property.',
      'Clear repayment track record of 12+ months on primary loan.',
      'No defaults or consecutive delays on EMIs.',
      'Outstanding property equity matches proposed top-up requirements.',
    ],
    documents: {
      salaried: [
        'Aadhaar Card and PAN Card.',
        'Last 3 Months Salary Slips (Salaried) or 2 Years ITR (Self Employed).',
        'Last 6 Months Bank Statement (showing active EMIs).',
        'Outstanding balance letter of the primary loan.',
      ]
    },
    processSteps: [
      'Submit your existing loan details and required top-up amount.',
      'Our experts verify repayment history and property valuation delta.',
      'Documentation is collected and linked with the active primary file.',
      'Fast-track approval and disbursement directly into account.',
    ],
    faqs: [
      { q: 'How is the maximum top-up loan amount calculated?', a: 'It is determined by your property\'s current market value minus the outstanding balance on your primary loan, subject to LTV limits.' },
      { q: 'Can I get a top-up loan from a different bank?', a: 'Yes, you can do a Home Loan Balance Transfer + Top-Up, switching your active loan to a cheaper bank and getting additional funds at the same time.' }
    ]
  }
};

interface Props {
  params: Promise<{ slug: string }>;
}

export async function generateMetadata(
  props: {
    params: Promise<{ slug: string }>;
  }
): Promise<Metadata> {
  const params = await props.params;
  const slug = params.slug;
  const product = PRODUCT_DATA[slug];
  if (!product) return {};

  const name = product.name;
  return {
    title: `${name} Gujarat | Premium Loan Advisor - Whitestone Fincorp`,
    description: `Compare and apply for a ${name} in Gujarat with Whitestone Fincorp. Get customized interest rates, simple documentation, and fast approvals from India's top banking partners.`,
    keywords: `${name} Gujarat, ${name} Ahmedabad, ${name} advisor Gujarat, ${name} consultant, Whitestone Fincorp`,
  };
}

export function generateStaticParams() {
  return Object.keys(PRODUCT_DATA).map((slug) => ({
    slug: slug,
  }));
}

export default async function ServiceSlugPage({ params }: Props) {
  const { slug } = await params;
  const product = PRODUCT_DATA[slug];

  if (!product) {
    notFound();
  }

  return (
    <div className="flex flex-col w-full bg-slate-50">
      {/* Hero Section */}
      <section className="relative pt-8 lg:pt-12 pb-16 bg-gradient-to-br from-slate-50 via-blue-50/20 to-slate-100/50 overflow-hidden">
        {/* Soft Background Blobs */}
        <div className="absolute top-20 left-10 w-80 h-80 rounded-full bg-[#0B4F9C]/5 blur-3xl -z-10 pointer-events-none" />
        <div className="absolute bottom-10 right-20 w-96 h-96 rounded-full bg-[#00A86B]/5 blur-3xl -z-10 pointer-events-none" />

        {/* Background Network Pattern */}
        <div className="absolute inset-0 opacity-[0.03] pointer-events-none -z-10" style={{ backgroundImage: 'url("data:image/svg+xml,%3Csvg width=\'60\' height=\'60\' viewBox=\'0 0 60 60\' xmlns=\'http://www.w3.org/2000/svg\'%3E%3Cg fill=\'none\' fill-rule=\'evenodd\'%3E%3Cg fill=\'%230B4F9C\' fill-opacity=\'1\'%3E%3Cpath d=\'M36 34v-4h-2v4h-4v2h4v4h2v-4h4v-2h-4zm0-30V0h-2v4h-4v2h4v4h2V6h4V4h-4zM6 34v-4H4v4H0v2h4v4h2v-4h4v-2H6zM6 4V0H4v4H0v2h4v4h2V6h4V4H6z\'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E")' }} />
        
        <div className="max-w-7xl mx-auto px-6 md:px-8 grid grid-cols-1 lg:grid-cols-12 gap-12 items-start relative z-10">
          <div className="lg:col-span-7 flex flex-col gap-6 text-center lg:text-left">
            <span className="text-xs font-extrabold uppercase tracking-widest text-[#00A86B] font-poppins">Product Overview</span>
            <h1 className="text-3xl md:text-5xl font-black text-slate-800 tracking-tight font-poppins leading-[1.1]">
              {product.name}
            </h1>
            <p className="text-xs md:text-sm text-slate-500 font-semibold leading-relaxed max-w-xl mx-auto lg:mx-0">
              {product.heroDesc}
            </p>

            {/* Core parameters box */}
            <div className="grid grid-cols-3 gap-4 p-5 bg-white border border-slate-100 rounded-2xl shadow-xs text-xs font-semibold text-slate-600 max-w-lg mx-auto lg:mx-0">
              <div className="flex flex-col text-center">
                <span className="text-slate-400 font-bold uppercase text-[9px] tracking-wider block">Interest Rate</span>
                <span className="text-slate-800 font-bold font-dmsans mt-1">{product.rates}</span>
              </div>
              <div className="flex flex-col text-center border-x border-slate-100">
                <span className="text-slate-400 font-bold uppercase text-[9px] tracking-wider block">Max Amount</span>
                <span className="text-slate-800 font-bold font-dmsans mt-1">{product.amount}</span>
              </div>
              <div className="flex flex-col text-center">
                <span className="text-slate-400 font-bold uppercase text-[9px] tracking-wider block">Max Tenure</span>
                <span className="text-slate-800 font-bold font-dmsans mt-1">{product.tenure}</span>
              </div>
            </div>

            {/* Premium Abstract Vector for Hero Fill */}
            <div className="hidden lg:flex flex-col mt-4 w-full max-w-lg mx-auto lg:mx-0">
              <div className="relative w-full h-48 rounded-3xl bg-white/50 backdrop-blur-sm border border-white shadow-xl shadow-blue-900/5 overflow-hidden flex items-center justify-center p-6">
                {/* Background grid texture */}
                <div className="absolute inset-0 opacity-[0.03] pointer-events-none" style={{ backgroundImage: 'url("data:image/svg+xml,%3Csvg width=\'60\' height=\'60\' viewBox=\'0 0 60 60\' xmlns=\'http://www.w3.org/2000/svg\'%3E%3Cg fill=\'none\' fill-rule=\'evenodd\'%3E%3Cg fill=\'%230B4F9C\' fill-opacity=\'1\'%3E%3Cpath d=\'M36 34v-4h-2v4h-4v2h4v4h2v-4h4v-2h-4zm0-30V0h-2v4h-4v2h4v4h2V6h4V4h-4zM6 34v-4H4v4H0v2h4v4h2v-4h4v-2H6zM6 4V0H4v4H0v2h4v4h2V6h4V4H6z\'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E")' }} />

                {/* Main Abstract Graphic Area */}
                <div className="relative w-full h-full flex flex-col justify-end">
                  {/* Subtle bar charts in background */}
                  <div className="absolute bottom-0 left-0 w-full flex items-end justify-between px-6 opacity-[0.15]">
                    <div className="w-6 h-8 bg-[#0B4F9C] rounded-t-sm" />
                    <div className="w-6 h-14 bg-[#0B4F9C] rounded-t-sm" />
                    <div className="w-6 h-10 bg-[#00A86B] rounded-t-sm" />
                    <div className="w-6 h-20 bg-[#0B4F9C] rounded-t-sm" />
                    <div className="w-6 h-16 bg-[#0B4F9C] rounded-t-sm" />
                    <div className="w-6 h-24 bg-[#00A86B] rounded-t-sm" />
                  </div>

                  {/* Smooth curved trendline SVG */}
                  <svg width="100%" height="100%" viewBox="0 0 500 200" preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg" className="absolute inset-0 drop-shadow-xl z-10">
                    <path d="M0,160 C80,160 120,90 200,100 C280,110 320,50 400,60 C450,65 480,30 500,20 L500,200 L0,200 Z" fill="url(#serviceTrendGradient)" />
                    <defs>
                      <linearGradient id="serviceTrendGradient" x1="0" y1="0" x2="0" y2="1">
                        <stop offset="0%" stopColor="#0B4F9C" stopOpacity="0.15" />
                        <stop offset="100%" stopColor="#0B4F9C" stopOpacity="0.0" />
                      </linearGradient>
                    </defs>
                    <path d="M0,160 C80,160 120,90 200,100 C280,110 320,50 400,60 C450,65 480,30 500,20" fill="none" stroke="#0B4F9C" strokeWidth="4" strokeLinecap="round" />
                    
                    {/* Glowing points */}
                    <circle cx="200" cy="100" r="4" fill="#0B4F9C" />
                    <circle cx="400" cy="60" r="4" fill="#0B4F9C" />
                    <circle cx="500" cy="20" r="6" fill="#00A86B" />
                    <circle cx="500" cy="20" r="14" fill="#00A86B" opacity="0.3" />
                  </svg>
                </div>
              </div>
            </div>
          </div>

          {/* Form */}
          <div className="lg:col-span-5">
            <ContactForm defaultLoanType={slug.toUpperCase().replace('-', '_')} />
          </div>
        </div>
      </section>

      {/* Main Details Section */}
      <section className="py-20 bg-white">
        <div className="max-w-7xl mx-auto px-6 md:px-8 grid grid-cols-1 lg:grid-cols-12 gap-12">
          {/* Detailed Criteria */}
          <div className="lg:col-span-8 flex flex-col gap-10">
            {/* Key Benefits */}
            <div className="flex flex-col gap-4">
              <h2 className="text-xl font-bold text-slate-800 font-poppins">Product Benefits</h2>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                {product.benefits.map((benefit, idx) => (
                  <div key={idx} className="flex gap-2.5 items-start p-4 bg-slate-50 border border-slate-100 rounded-xl">
                    <CheckCircle2 size={16} className="text-[#00A86B] shrink-0 mt-0.5" />
                    <span className="text-xs font-semibold text-slate-600 leading-relaxed">{benefit}</span>
                  </div>
                ))}
              </div>
            </div>

            {/* Eligibility Criteria */}
            <div className="flex flex-col gap-4">
              <h2 className="text-xl font-bold text-slate-800 font-poppins">Eligibility Guidelines</h2>
              <div className="grid gap-2.5">
                {product.eligibility.map((rule, idx) => (
                  <div key={idx} className="flex gap-2.5 items-start text-xs font-semibold text-slate-600">
                    <div className="w-1.5 h-1.5 rounded-full bg-[#0B4F9C] shrink-0 mt-1.5" />
                    <span className="leading-relaxed">{rule}</span>
                  </div>
                ))}
              </div>
            </div>

            {/* Documentation */}
            <div className="flex flex-col gap-4">
              <h2 className="text-xl font-bold text-slate-800 font-poppins">Documents Required</h2>
              <div className="p-6 rounded-2xl bg-slate-50 border border-slate-100 flex flex-col gap-3">
                <div className="flex items-center gap-2 pb-2 border-b border-slate-200/50">
                  <FileText size={18} className="text-[#0B4F9C]" />
                  <span className="text-sm font-bold text-slate-800">Required Document Checklist</span>
                </div>
                <div className="grid gap-2 mt-2">
                  {product.documents.salaried.map((doc, idx) => (
                    <div key={idx} className="flex gap-2 items-start text-xs font-semibold text-slate-600">
                      <div className="w-1.5 h-1.5 rounded-full bg-[#00A86B] shrink-0 mt-1.5" />
                      <span>{doc}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>

            {/* Process Timeline */}
            <div className="flex flex-col gap-5">
              <h2 className="text-xl font-bold text-slate-800 font-poppins">How to Apply & Processing Flow</h2>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                {product.processSteps.map((step, idx) => (
                  <div key={idx} className="p-4 rounded-xl border border-slate-100 bg-white shadow-xs flex gap-3 items-center">
                    <div className="w-8 h-8 rounded-lg bg-blue-50 text-[#0B4F9C] font-bold text-xs flex items-center justify-center font-dmsans">
                      {idx + 1}
                    </div>
                    <span className="text-xs font-semibold text-slate-600">{step}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* Product Sidebar FAQ */}
          <div className="lg:col-span-4 flex flex-col gap-6">
            <div className="bg-slate-50 p-6 md:p-8 rounded-3xl border border-slate-100 shadow-xs flex flex-col gap-5">
              <div className="flex items-center gap-2 pb-2 border-b border-slate-200">
                <HelpCircle size={18} className="text-[#0B4F9C]" />
                <h3 className="text-sm font-bold text-slate-800 font-poppins">Product FAQ</h3>
              </div>
              <div className="flex flex-col gap-4">
                {product.faqs.map((faq, idx) => (
                  <div key={idx} className="flex flex-col gap-1.5">
                    <span className="text-xs font-bold text-slate-800 font-poppins">{faq.q}</span>
                    <span className="text-[11px] font-semibold text-slate-500 leading-relaxed">{faq.a}</span>
                  </div>
                ))}
              </div>
            </div>

            {/* Quick Links */}
            <div className="bg-[#0B4F9C]/5 p-6 rounded-3xl border border-[#0B4F9C]/10 flex flex-col gap-4 text-center">
              <span className="text-xs font-bold text-slate-700">Not sure about borrowing limit?</span>
              <Link
                href="/calculators/eligibility"
                className="w-full py-2.5 rounded-xl bg-[#0B4F9C] text-white text-xs font-bold shadow-xs hover:bg-[#083c78] transition-colors flex items-center justify-center gap-1"
              >
                Use Eligibility Checker <ArrowRight size={14} />
              </Link>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
